### ISSUE TITLE
[RFC] V3 Scheduler cog

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#101]
I'll be ensuring Red has a functional scheduler cog ready prior to the stable release of V3. This issue serves as an open forum for any features people want to request for it.

**Comment by calebj** [comment]
As discussed on Discord, I'd like to be able to use the scheduler internals and task storage via an API, and be able to programmatically schedule callbacks to functions.

This would require an interface for creating, listing, and removing scheduled events, with optional JSON serializable metadata. Repeating events, too.

As for implementation specifics: unique string keys might be necessary for simplicity, combined with some kind of priority queue for the timestamps associated with the next invocation. The callback would probably follow a standard convention of
```py
async def cb_func_name(handle: scheduler.Handle, overdue: float)
```
where the custom data, if any, is accessible as `handle.data`.

A proper index for the database would help a lot for knowing what events should be called next (or have been called in the past), but nothing in Config can use them because of the JSON lowest common denominator. The approach that has worked for me is to dump everything into a priority queue, then have the next 30 or so seconds of events scheduled with `loop.call_later()`. The timestamps to be called can be loaded into the queue on startup and updated in memory as needed. A mapping between cogs and their task IDs might also speed up some get operations.

If the call fails, it should either a) keep trying or b) drop it. The retry behavior is only one of several parameters that would be passed to the creation function.

**Comment by mikeshardmind** [comment]
command scheduler is out now, a similar API for internal use will be handled by an open PR being worked instead. (Cog-Creators/Red-DiscordBot#2247)
