### ISSUE TITLE
[RoleManagement] Suggestion about selfadd and selfrem

### ISSUE THREAD

**Issue by Dezyox** [mikeshardmind/SinbadCogs#158]
For RoleManagement, a command to make all roles self assignable and self removable, set or not
Also, probably to let the owner to choose if when a guild is joined, Red automatically active selfadd selfrem

**Comment by mikeshardmind** [comment]
> For RoleManagement, a command to make all roles self assignable and self removable, set or not

Not happening. The settings are there so that things like admin roles are never accidentally handed out.

> Also, probably to let the owner to choose if when a guild is joined, Red automatically active selfadd selfrem

Absolutely not. While I have no issue with an owner going onto a server to help them set up their server, I do have an issue with this just allowing roles to be given out by mere existence on a bot. This cog will never do something it wasn't explicitly asked to do. Giving out roles just by inviting a bot isn't okay.
