### ISSUE TITLE
[RSS] Reposting rss items

### ISSUE THREAD

**Issue by j0w0** [mikeshardmind/SinbadCogs#173]
The RSS cog posts items multiple times with this specific feed. What seems to be happening is this feed is posting the same item again (possibly to update the comment statistic?)
This is the feed that I'm using: https://gbatemp.net/forums/gbatemp-scene-news.101/index.rss

**Comment by Spyneur** [comment]
Same problem here, with Steam link in my case :

![2019-11-23_19-07-24](https://user-images.githubusercontent.com/15103741/69483227-e31a8900-0e24-11ea-8178-fea313f4845f.png)
![2019-11-23_19-07-07](https://user-images.githubusercontent.com/15103741/69483230-ec0b5a80-0e24-11ea-8633-e8e0258bf6ed.png)
![2019-11-23_19-06-46](https://user-images.githubusercontent.com/15103741/69483232-edd51e00-0e24-11ea-89f7-22030c00d184.png)

I'm not sure what the problem is, but one link is a annoucement when the other one seems to be an event link. 

![2019-11-23_19-18-23](https://user-images.githubusercontent.com/15103741/69483315-0eea3e80-0e26-11ea-9a5b-95e4a267d92d.png)
![2019-11-23_19-18-07](https://user-images.githubusercontent.com/15103741/69483316-13aef280-0e26-11ea-9bbd-5b1f0c58aa66.png)

This is the source code for one of RSS Steam link (Garry's Mod)

![2019-11-23_19-15-18](https://user-images.githubusercontent.com/15103741/69483284-997e6e00-0e25-11ea-8e64-b5c84dd7d1ec.png)

If this help to find the problem :/

**Comment by mikeshardmind** [comment]
Hmm. I will take a closer look at this soon.

**Comment by Brandjuh** [comment]
I had this problem also with a few feeds, I removed them, since the site where I used it from had a auto-refresh that also refreshed there RSS. I asked them to change that, but they removed the RSS feature in stead under the name "Old-unused function"

**Comment by mikeshardmind** [comment]
[Won't be worked around](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md) (Though this is still ultimately an issue with specific feeds)
