### ISSUE TITLE
V3 RSS

### ISSUE THREAD

**Issue by JoeKoen** [mikeshardmind/SinbadCogs#192]
RSS Feed unable to ping @everyone 

![image](https://user-images.githubusercontent.com/19499442/72546116-307d0a80-3858-11ea-8f31-3513ed11d0b1.png)

Using the latest latest update, made sure to remove the cog and repo and redownload

**Comment by mikeshardmind** [comment]
This is quite literally by design and not an issue with the cog. There are too many services that provide content that could cause accidental mass mentions. On top of this, there are many services with RSS feeds that re-send for edited content which has not changed location. There is no additional handling in the cog for the latter, and the former literally can't be safely changed.

**Comment by JoeKoen** [comment]
anyway to make it at everyone, or toggle it?

**Comment by mikeshardmind** [comment]
No.
> the former literally can't be safely changed.

If you'd like to see this changed, you'll have to wait until discord handles the issues around this, which appears to be scheduled somewhere between the heat death of the universe and never on their agenda.

**Comment by JoeKoen** [comment]
okay, well thanks for the replies! good work on the cogs !
