### ISSUE TITLE
Should Red users be informed of why these are no longer supported?

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/SinbadCogs#208]
You placed a file in the repository with the info, is this something cog users should know?

**Comment by mikeshardmind** [comment]
No. At no point did I use Red's functionality to announce these sorts of things. It's not appropriate to change that.

**Comment by mikeshardmind** [comment]
To preempt the anticipated follow-up question: No, public good is not a good enough argument to change my mind here. People are responsible for being aware of what they use. Creators should be responsible when deciding what they choose to create.

**Comment by DiscordLiz** [comment]
I still think you should be telling users. There are functions in the bot for that, it isn't overreaching even if you haven't needed to before.

Most users won't ever see your notice about the cogs not being updated, they will just find out when something eventually breaks. I think you should say why too. It's info people need to be able to make the informed decision you mentioned, and users just won't see it here.

If you still disagree, I won't bring it up again, but I think this is a great opportunity to drop it all with a sense of finality.

**Comment by mikeshardmind** [comment]
If you want to talk about this later, we can. I'd prefer to think about some things first, maybe take a week or two with no notifications at all after all the DMs, comments on things, and even emails I got about this. (which is part of why I don't think it exactly needs to be said, people have seen it already)

I won't make a decision on this right now, but I will make a decision on this. It is time for me to close this all up, but I'm not in any rush. The related reasons won't just change overnight, and the history is in the past where it can only be stated as "here's what happened"

Doing any more than what has been done can wait until I decide if it even needs doing, and if so how and only under those conditions, after it is done properly.

**Comment by mikeshardmind** [comment]
I've closed some open issues so that people don't get the wrong idea about me continuing with entertaining them. I'll handle something with this last issue later as a final state of things.

**Comment by Twentysix26** [comment]
Since you decided to make it personal and it's starting to look more and more like a smear campaign against the project as a whole I'd like to make a few observations about some of the points you just wrote
> While the two quotes above are from direct messages, as it reflects on the project as coming from
**the person in charge of the project while speaking about the project**,  


In case you somehow managed to completely forget it in the past two days, I haven't done any active Red development in the past 2 years, nor I took any action in the organization that would make me "the person in charge". I'm co-owner of the _external organization_ and I'm _one_ of the admins in the Discord server. I don't even take important server-related decisions without consulting the other admins. I guess that "one of the admins" just doesn't sound as good as "the person in charge" when you're trying to further your own agenda though.  
I have to admit it is particularly funny you call me that, as most people who haven't been around for long would've probably thought of *you* as the project leader, due to the sheer amount of contributions and design decisions you took during your time.  

> "having now seen the original conversation it's... really not that bad."
> "I especially hope not to see this kind of stuff again (which I understand it's on your personal repo but it still has visibility)"

I wonder why you have only posted two sentences and not the whole conversation we've had. Probably because it would not paint me as the one sided "person in charge" that you're trying to pass me off as, but rather as the impartial figure I've been trying to be when you decided to take your leave and shit on everyone on your way out.  
So yeah, forgive me if *after* you left I tried to understand what the hell was going on, took everyone's side of the story in private and tried to put the fires out while staying impartial.
And I do regret not acting sooner, since I did know that there was *something* going on, but I was hoping that you *as a team* would finally clear things up and would not need an admin to step in.
I'm not blaming you for leaving. I'm not blaming anyone for what happened. The lack of attempting a discussion, because that's ALL you needed to do to fix this, is on the whole team.  

I do stand by my statement, "it wasn't that bad" of a situation. People talk. All the time. Everywhere, from open source to the workplace. It's a reality of life. Sometimes they have a reason, sometimes they're dicks. All you had to do was stop for a second and attempt a conversation with them, try to see their point of view on why they're unhappy about certain things. Hell, you could've asked me and I would've gladly mediated things, peacekeeping is part of our duties.

You stated multiple times that you wanted to leave for your own reasons sooner or later, I really don't get why you decided to leave on such a bad note, blowing out of proportion what seemed to be nothing more than a few watercooler talks. Nobody is out to get you dude. You decided to leave, that's your choice, now have the decency to understand that it's also time to stop.

**Comment by mikeshardmind** [comment]
I'm not here to argue facts, and I'm not going to get into a back and forth. I've spent more energy than I wanted on this already, and have basically been drowning in DMs on discord prior to any of this. All over a decision to quit without informing people of all the details. I post any details at all, and I get issue comments and DMs justifying behavior that led to me quitting. I'm tired, and I don't have energy to spend on this anymore. 

What I've posted reflects what has happened and my perspective. I'm not claiming to be some picture of perfection in any of it. But I will not spend more energy on this. I'm disappointed that I had to delete a comment here over this, especially since it was posted about 10 minutes after my status on discord switched to offline. Much as I didn't go using Red's announcement channels to tell the project what happened, I don't need or want any of this in my issue feed. 

Leave me alone go make whatever alternative you want. Fork it and move on if you want, I chose a permissive license because people should have that ability.
