### ISSUE TITLE
[RoleManagement] Suggestion | Roleset

### ISSUE THREAD

**Issue by Menteroth** [mikeshardmind/SinbadCogs#209]
**Describe the solution you'd like**
When setting roles exclusive to each other it would be nice to have the bot remove the reaction your first chose if you react with something else later. So that if you need/want to go back to the initial reaction you don't have to unreact before reacting again. Plus it also shows the correct number of reactions compared to roles added to members.

**Comment by mikeshardmind** [comment]
[Won't be added](https://github.com/mikeshardmind/SinbadCogs/blob/v3/why_no_support.md)

**Comment by mikeshardmind** [comment]
As there's [new attention on this ](https://cogboard.red/t/paid-10-update-rolemanagement-by-sinbadcogs/664) since supporting again...

The "won't be added" bit was a glib quick response that didn't deal with explaining why this change is not easily compatible with the cog.

Discord does not send information about who removed the reaction in the same payload as the reaction events (it *is* inconsistently available from the audit log) This also increases the rate limit consumption, the number of reactions matching is also not something this achieves, as discord does not send the full reaction info to the desktop or mobile clients.

This could lead to conditions that are messy to deal with properly and I cannot suggest this, despite agreeing that in a perfect scenario, if the roles were set as exclusive, this would be done.
